tables: fix double quotes for C# compatibility
nspcc-dev/go-ordered-json pull request #9
Opened 2024-01-10 11:19 UTC by AliceInHunterland

Ref nspcc-dev/neo-go#2319.

2024-01-10 13:52 UTC, AnnaShaleva reviewed
Good, the fix itself looks legit, need to fix the rest of tests. I'll check the mainnet with it.

2024-01-10 13:52 UTC, AnnaShaleva commented on encode.go
> +			case '\\':
Need to adjust comment to `default` case.

2024-01-10 13:53 UTC, AnnaShaleva commented
We also need to check that deserialization worksproperly.

2024-01-10 13:56 UTC, AnnaShaleva commented
BTW, wrong issue reference.

2024-01-11 07:35 UTC, AnnaShaleva reviewed
Otherwise LGTM.

2024-01-11 07:35 UTC, AnnaShaleva commented on encode.go
> +				// This encodes bytes < 0x20 and "" except for \t, \n and \r.
It's a single quote.

2024-01-11 07:35 UTC, AnnaShaleva commented on encode_test.go
> -
Useless change.

2024-01-11 07:35 UTC, AnnaShaleva commented on encode_test.go
> +	{`{"p":"neoz-20","op":"deploy","tick":"neoz","max":"21000000","lim":"1000"}`, `"{\u0022p\u0022:\u0022neoz-20\u0022,\u0022op\u0022:\u0022deploy\u0022,\u0022tick\u0022:\u0022neoz\u0022,\u0022max\u0022
Not related to this repo, we'd better have this test in NeoGo.

2024-01-11 07:59 UTC, AnnaShaleva approved these changes
Good, waiting for mainnet/testnet states confirmation before the merge.

2024-01-11 08:03 UTC, AnnaShaleva requested changes
Adjust commit message wrt PR title and change issue in the commit body.

2024-01-11 20:54 UTC, AliceInHunterland commented
> Good, waiting for mainnet/testnet states confirmation before the merge.

```
ekaterina@ekaterina-ThinkPad-T14-Gen-1:~/Desktop/neo-go$ go run scripts/compare-states/compare-states.go http://localhost:10332 http://seed1.neo.org:10332 
at 0: 58a5157b7e99eeabf631291f1747ec8eb12ab89461cda888492b17a301de81e8 vs 58a5157b7e99eeabf631291f1747ec8eb12ab89461cda888492b17a301de81e8
at 4716143: a64d3eaec83ab6c45f34136bcb4473d0f12821c283440f297e2c69fdc1d78886 vs a64d3eaec83ab6c45f34136bcb4473d0f12821c283440f297e2c69fdc1d78886
```

```
ekt@ekt:~/neo-go$ go run ./scripts/compare-states/compare-states.go http://localhost:20332 http://seed1t5.neo.org:20332
at 0: 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b vs 62fd8ff9b0543aea352257db5b00bbb01d1bc0d2cc665e1f24cf5de0d16ebc7b
at 3320969: 7cbac469505835bd8d9c6a5bc84172d4234b0d04235b936ee3f391bff6120e29 vs 7cbac469505835bd8d9c6a5bc84172d4234b0d04235b936ee3f391bff6120e29
```

2024-01-12 07:41 UTC, AnnaShaleva approved these changes

2024-01-12 07:41 UTC, merged